# Application configuration for sb3_2_saml
#
# This example uses SAML2 login. To integrate with your Identity Provider (IdP),
# you typically need to provide the IdP metadata URL and configure a relying party
# registration. Spring Boot can auto-bind these properties.
#
# NOTE: The application will start without these properties, but SAML login will
# not function until a registration is configured. Secure endpoints will still
# be testable with mocked authentications in unit tests.

server:
  port: 8080

spring:
  application:
    name: sb3_2_saml

  # SAML2 configuration example (uncomment and adapt to your IdP)
  # security:
  #   saml2:
  #     relyingparty:
  #       registration:
  #         myidp:
  #           # Your application's entity ID (SP entity ID)
  #           entity-id: "urn:example:sb3_2_saml"
  #           # IdP metadata URL (or file path). Spring will fetch SSO/SLO bindings and signing keys.
  #           identityprovider:
  #             metadata-uri: "https://idp.example.com/metadata"
  #           # Optional: Signing/Decryption credentials for SP (if required by your IdP)
  #           # signing:
  #           #   credentials:
  #           #     - private-key-location: "classpath:credentials/sp-signing.key"
  #           #       certificate-location: "classpath:credentials/sp-signing.crt"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
